# Generated by Django 6.0.4 on 2026-04-09 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Госномер')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('mileage', models.IntegerField(default=0, verbose_name='Пробег')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
