# Generated by Django 6.0.4 on 2026-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_mechanic_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
