# Generated by Django 6.0.4 on 2026-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='checklist_template',
            field=models.TextField(blank=True, help_text='Пункты чек-листа, каждый с новой строки'),
        ),
    ]
