# Generated by Django 6.0.4 on 2026-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_checklist_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='checklist_template',
        ),
        migrations.AddField(
            model_name='service',
            name='checklist_items',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки', verbose_name='Пункты чек-листа'),
        ),
    ]
